### ISSUE TITLE
Define runtime operations for OpValue

### ISSUE THREAD

**Issue by Roger-luo** [Roger-luo/Liang.jl#22]
we need some basic evaluation routines of the `OpValue` (regardless of what variant it is):

- [x] add/sub: add up two `OpValue`
- [x] multiply: mul two `OpValue` and mul a `OpValue` with a Vector
- [x] Kronecker mul
- [x] trace
- [x] det
- [x] partial trace

**Comment by weinbe58** [comment]
we should also allow mixing between `Num` and `OpValue`.
